language: python
python:
  - 3.4
  - 2.7
script: make test
notifications:
  email: false
env:
  matrix:
    - DJANGO='django>=1.6,<1.7'
    - DJANGO='django>=1.7,<1.8'
install:
  - psql -c 'CREATE DATABASE encrypted_field' -U postgres
  - pip install -r test_requirements.txt
  - pip install $DJANGO coveralls
after_success:
  coveralls
